name: ar_demo
description: An ar demo
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_unity_widget: ^4.0.1+1
  cupertino_icons: ^1.0.2
  http: ^0.13.1
  xml2json: ^5.0.0
  flutter_html: ^1.3.0
  firebase_core: ^1.0.2
  path_provider: ^2.0.1
  firebase_ml_vision:
    git:
      url: git://github.com/algirdasmac/flutterfire
      path: packages/firebase_ml_vision

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
